#!/bin/sh

set -e

PREREQ="zfs"
prereqs() {
    echo "$PREREQ"
}

case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

# shellcheck disable=SC1091
. /scripts/functions

rollback() {

    log_begin_msg "Import ZFS pools"
    zpool import -a
    log_end_msg

    log_begin_msg "List ZFS datasets"
    zfs list
    log_end_msg

    log_begin_msg "Rollback to initial state"
    zfs rollback -r 'rpool/ROOT/ubuntu@current'
    zfs rollback -r 'bpool/BOOT/ubuntu@current'
    log_end_msg

    log_success_msg "Device restaured to initial state"

    echo "Press any key to shutdown the computer"
    read -r

    poweroff -f
}

# check kernel command line and look for a rollback argument
for arg in $(/proc/cmdline); do
    if [ "$arg" = "rollback" ]; then
        rollback
    fi
done
