#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

submenu 'Restore computer to initial state' {
    menuentry 'Nope, I mistyped, sorry' {
        echo 'OK, shuting down then...'
        halt
    }
    menuentry 'Yes, restore computer to initial state!' {
        load_video
        insmod gzio
        insmod part_gpt
        insmod zfs
        set root='hd0,gpt2'
        echo 'Loading Linux...'
        linux "/BOOT/ubuntu@/vmlinuz" root=ZFS="rpool/ROOT/ubuntu" rollback
        echo 'Loading initial ramdisk...'
        initrd "/BOOT/ubuntu@/initrd.img"
    }
}