:experimental:
:icons: font

[[firmware-config]]
== Configuration du firmware

Pour accéder à la configuration du firmware, allumer l'ordinateur, puis appuyer 
rapidement sur la touche kbd:[Enter] comme indiqué lorsque le logo
_Lenovo (TM)_ apparaît à l'écran.

NOTE: Ne pas hésiter à marteler la touche kbd:[Enter] jusqu'à ce qu'un bip
retentisse, synonyme de succès dans l'accès au menu de démarrage.

Un menu de démarrage s'affiche à l'écran, avec plusieurs options.

Appuyer sur kbd:[F1] pour accéder à la configuration du firmware (`F1 to enter the BIOS Setup Utility`).

=== Désactivation du « Secure Boot »
Aller sur l'écran de configuration menu:Security[Secure Boot] et modifier les paramètres comme suit :

[horizontal]
`Secure Boot`:: `[Disabled]`

=== Virtualisation
Aller sur l'écran de configuration menu:Security[Virtualization] et modifier
les paramètres comme suit :

[horizontal]
`Intel \(R) Virtualization Technology`:: `[Enabled]`
`Intel \(R) VT-d Feature`:: `[Enabled]`

=== Configuration du clavier
Aller sur l'écran de configuration menu:Config[Keyboard/Mouse] et modifier
les paramètres comme suit :

[horizontal]
`Fn and Ctrl Key swap`:: `[Enabled]`
`F1-F12 as Primary Function`:: `[Enabled]`

Une fois toutes les modifications effectuées, sélectionner
menu:Restart[Exit Saving Changes], puis appuyer sur kbd:[↵] pour sauvegarder
la configuration et redémarrer l'ordinateur.