:experimental:
:icons: font
:toc:

== Installation d'Ubuntu

Nous allons dérouler l'installation du système d'exploitation Ubuntu sur un
système de fichiers ZFS, ceci pour bénéficier des possibilités offertes par
ZFS pour restaurer facilement les PC de formation dans un état donné.

Pour dérouler l'installation, il faut télécharger une image disque
link:http://releases.ubuntu.com/18.04/ubuntu-18.04.2-desktop-amd64.iso[d'Ubuntu 18.04 64 bits Desktop,window=_blank],
et créer une clé USB de démarrage à partir de cette image
footnote:[Didacticiel de création d'une clé USB de démarrage d'Ubuntu : https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-ubuntu].

=== Démarrage d'une session _live_ d'Ubuntu

. Insérer la clé de démarrage d'Ubuntu dans un port USB de l'ordinateur ;
. allumer ou redémarrer l'ordinateur, puis faire afficher le menu de démarrage
(voir  _<<firmware-config>>_) ;
. appuyer sur kbd:[F12] pour sélectionner le périphérique de démarrage
(`F12 to choose a temporary starting device`) ;
. sélectionner le périphérique correspondant à la clé USB de démarrage
d'Ubuntu, puis valider avec kbd:[Enter] ;
. dans le menu GRUB, sélectionner `Try Ubuntu without installing`, puis valider
avec kbd:[Enter]. 

=== Installation

IMPORTANT: La procédure détaillée ci-dessous nécessite que l'ordinateur ait
accès à Internet.

==== Préparation de l'environnement d'installation

. Ouvrir un terminal ;
. activer le dépôt `universe` :
+
```shell
$ sudo apt-add-repository universe
```
. Devenir `root` :
+
```shell
$ sudo -s
```
. installer les paquets nécessaires au formattage du disque :
+
```shell
# apt install -y debootstrap gdisk zfs-initramfs
```

==== Formattage du disque

. Identifier le disque à utiliser pour l'installation :
+
```shell
$ ls -la /dev/disk/by-id
```
Repérer dans ce dossier le lien symbolique vers le _block device_ `/dev/nvme0nX`
footnote:[Ne pas confondre le _block device_ `/dev/nvme0nX` avec le _character
device_ `/dev/nvme0`. Le premier représente un disque – sur lequel on veut
écrire concrètement – alors que le second représente le contrôleur NVME de
l'ordinateur]
, où `X` est un chiffre (le lien symbolique ver `/dev/nvme0n1` normalement
dans notre cas).
+
NOTE: On utilisera le chemin `/dev/disk/by-id/my-disk` en guise d'exemple dans
la suite de cette documentation.
+
[WARNING]
====
Le didacticiel utilisé comme base à cette documentation préconise d'utiliser
les alias par identifiants (`/dev/disk/by-id/\*`) et non les chemins directs
aux _block devices_ (`/dev/nvme0n*`) pour toutes les commandes concernant ZFS.
====

. effacer la table de partition du disque :
+
```shell
# sgdisk --zap-all /dev/disk/by-id/my-disk
```

. partitionner le disque :
    * créer une partition UEFI :
+
```shell
# sgdisk -n2:1M:+512M \ // <1>
    -t2:EF00 \ // <2>
    /dev/disk/by-id/my-disk
```
<1> Créer une nouvelle partition numérotée `2`, à 1 Mio
footnote:[Mio pour « mébioctet ». 1 Mio = 2^20^ octets = 1 048 576 octets, alors que 1 Mo = 10^6^ octets = 1 000 000 octets. Voir https://fr.wikipedia.org/wiki/Octet] du début du disque, de taille 512 Mio.
<2> Spécifie le type de la partition `2`, ici, `EF00` désigne une partition système EFI
footnote:[Voir les différents types de partitions : https://wiki.archlinux.org/index.php/GPT_fdisk#Partition_type].

    *  [[boot-pool-partition]] créer une partition de démarrage :
+
```shell
# sgdisk -n3:0:+512M \
    -t3:BF01 \
    /dev/disk/by-id/my-disk
```

    * créer une partition racine :
+
```shell
# sgdisk -n4:0:0 \
    -t4:BF01 \
    /dev/disk/by-id/my-disk
```

==== Configuration ZFS

. Créer les _pools_ ZFS

    * Créer le _pool_ de démarrage :
+
```shell
# zpool create -o ashift=12 \ //<1>
      -d \ //<2>
      -o feature@async_destroy=enabled \
      -o feature@bookmarks=enabled \
      -o feature@embedded_data=enabled \
      -o feature@empty_bpobj=enabled \
      -o feature@enabled_txg=enabled \
      -o feature@extensible_dataset=enabled \
      -o feature@filesystem_limits=enabled \
      -o feature@hole_birth=enabled \
      -o feature@large_blocks=enabled \
      -o feature@lz4_compress=enabled \
      -o feature@spacemap_histogram=enabled \
      -o feature@userobj_accounting=enabled \
      -O acltype=posixacl \
      -O canmount=off \ // <3>
      -O compression=lz4 \
      -O devices=off \
      -O normalization=formD \
      -O relatime=on \
      -O xattr=sa \
      -O mountpoint=/ \
      -R /mnt \ // <4>
      bpool \ // <5>
      /dev/disk/by-id/my-disk-part3 // <6>
```
<1> Exposant de la taille de secteur du _pool_. On positionne la valeur de
`ashift` à 12 pour correspondre à la taille de secteur de 4096 (2^12^) octets
des disques modernes
footnote:[Note sur les disque AF (Advanced Format) : https://github.com/zfsonlinux/zfs/wiki/faq#advanced-format-disks].
<2> Seules les propriétés supportées par Grub sont activées individuellement.
<3> Propriétés du système de fichiers.
<4> Point du montage du _pool_.
<5> Nom donné au _pool_.
<6> _Block device_ utilisé pour créer le _pool_. Il s'agit de la partition créer <<boot-pool-partition, ci-dessus>>.

    * Créer le _pool_ racine :
+
```shell
# zpool create -o ashift=12 \
      -O acltype=posixacl \
      -O canmount=off \
      -O compression=lz4 \
      -O dnodesize=auto \
      -O normalization=formD \
      -O relatime=on \
      -O xattr=sa \
      -O mountpoint=/ \
      -R /mnt \
      rpool \
      /dev/disk/by-id/my-disk-part4
```

. Créer les _datasets_

    * Créer les _datasets_ qui feront office de conteneurs, sur chacun
    des deux _pools_ :
+
```shell
# zfs create -o canmount=off -o mountpoint=none rpool/ROOT
# zfs create -o canmount=off -o mountpoint=none bpool/BOOT
```
    * Créer et monter le _dataset_ du système de fichier racine :
+
```shell
# zfs create -o canmount=noauto -o mountpoint=/ rpool/ROOT/ubuntu
# zfs mount rpool/ROOT/ubuntu
```
    * Créer et monter le _dataset_ du système de fichier de démarrage:
+
```shell
# zfs create -o canmount=noauto -o mountpoint=/boot bpool/BOOT/ubuntu
# zfs mount bpool/BOOT/ubuntu
```

[NOTE]
====
Dans le cas d'une installation classique, on créerait d'autres _datasets_,
chacun configuré avec des options précises selon les points de montage
(`/tmp`, `/var/log`, `/var/cache`…). Compte tenu de l'usage particulier
qu'il sera fait de cette installation, nous nous contenterons des deux
datasets ci-dessus.
====

==== Installation et configuration du système

. Installer un système minimal :
+
```shell
# debootstrap bionic /mnt
# zfs set devices=off rpool
```

. Configurer le système

    * Configurer le nom d'hôte de la machine (`my-laptop` dans les
exemples ci-dessous) :
+
```shell
# echo "my-laptop" > /mnt/etc/hostname
# echo "127.0.1.1       my-laptop" >> /mnt/etc/hosts
```

    * Configurer l'interface réseau :
    ** Identifier le nom de l'interface réseau à configurer :
+
```shell
# ip addr show
```
+
NOTE: On utilisera le nom d'interface `eth0` dans l'exemple ci-dessous

    ** Créer le fichier `/mnt/etc/netplan/01-netcfg.yaml` avec le contenu
suivant :
+
```yaml
network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
```
+
NOTE: La configuration ci-dessous est simple et repose sur DHCP. Adapter
la configuration suivant les besoins.

    * Configurer les sources des paquets logiciels
+
```shell
# echo -e "deb http://security.ubuntu.com/ubuntu bionic-security main universe\ndeb http://archive.ubuntu.com/ubuntu bionic-updates main universe" >> /mnt/etc/apt/sources.list
```

    * Lier le système de fichiers virtuels de l'environnement _live_ au 
nouveau système et `chroot` :
+
```shell
# mount --rbind /dev  /mnt/dev
# mount --rbind /proc /mnt/proc
# mount --rbind /sys  /mnt/sys
# chroot /mnt /bin/bash --login
```


TO BE CONTINUED… §4.5