:experimental:
:icons: font

== Licence Windows

Avant d'installer un OS Linux en remplacement du Windows 10 pré-installé, il
convient de sauvegarder la clé de licence de Windows afin de pouvoir la
réutiliser lors de l'installation éventuelle de Windows 10 dans une machine
virtuelle.

. Démarrer l'ordinateur et ouvrir une session Windows ;
. lancer _Windows Powershell_ en mode _Administrateur_ depuis le menu démarrer ;
+
NOTE: Pour lancer un logiciel en mode _Administrateur_, faire un clic droit sur
l'icône du programme, puis cliquer sur _Exécuter en tant qu'administrateur_.
. installer les outils _Chocolatey_
footnote:chocolatey[Installation de _Chocolatey_ depuis PowerShell : https://chocolatey.org/install#install-with-powershellexe.]
et _The Magical Jelly Bean Keyfinder_
footnote:[Installation de _The Magical Jelly Bean Keyfinder_ avec Chocolatey : https://chocolatey.org/packages/keyfinder.]
en exécutant la commande suivante dans la console PowerShell :
+
```powershell
Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')); choco install -y keyfinder
```
+
IMPORTANT: L'ordinateur doit avoir accès à Internet pour dérouler
l'installation.
. lancer _Keyfinder_ depuis le menu démarrer ;
. sauvegarder la version de Windows, le _Product ID_ et la _CD Key_, pour réutilisation future.